
version: '3.8'

services:
  backend:
    build: ./services/backend
    ports:
      - 8000:8000
    volumes:
      - ./services/backend/api:/api/api
      - ./services/backend/prisma:/api/prisma
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app

  db:
    image: "postgres:latest"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app

volumes:
  postgres_data:

networks:
  app:
    driver: bridge